<b>T&#201;RMINOS Y CONDICIONES</b><p><a href="#english-tc">English Version</a>
</p>
<p>Es de su responsabilidad leer y comprender los t&#233;rminos y condiciones. Si tuviese cualquier tipo de inquietud, no dude en contactarse con Orbyta Mobile al tel&#233;fono de soporte o casilla de correo se&#241;alados en la p&#225;gina web.
 Antes de que usted apriete el bot&#243;n de &#8220;aceptar&#8221;, por favor lea de manera atenta y cuidadosa los t&#233;rminos y condiciones presentados a continuaci&#243;n. Al apretar el bot&#243;n &#8220;aceptar&#8221;, usted queda vinculado y comienza a formar parte de este contrato. Nos reservamos el derecho de enmendar este contrato de arriendo en cualquier momento. cualesquiera de estos cambios ser&#225;n aplicados a futuros arriendos despu&#233;s de la fecha en que dichos cambios hayan entrado en vigencia. </p>
<p>Orbyta Mobile LLC (&#8220;Orbyta Mobile&#8221;), y usted (el &#8220;Cliente&#8221;) acuerdan los siguientes t&#233;rminos y condiciones:</p>
<p>Orbyta Mobile proveer&#225; un servicio de arriendo de un modem inal&#225;mbrico (el &#8220;Pocket wi fi&#8221;), junto con gu&#237;as para el usuario y los accesorios correspondientes (en conjunto llamados &#8220;el Equipo&#8221;) a viajeros que planeen visitar Estados.</p>
<p>Si bien nuestro Equipo puede ser usado por viajeros de todas las edades, s&#243;lo se les dar&#225; en arriendo a adultos mayores de los 18 a&#241;os de edad, que sean plenamente capaces y competentes de comprender y satisfacer los t&#233;rminos, condiciones, obligaciones, afirmaciones, representaciones y garant&#237;as expuestas y enunciadas en este Contrato de Arriendo, obedeciendo y cumpliendo los T&#233;rminos y Condiciones expuestos en el presente documento.</p>
<p>Usted est&#225; de acuerdo en dar un trato cuidadoso al Equipo, y de manejar todas sus partes de acuerdo con lo estipulado en la gu&#237;a del usuario. As&#237; mismo, usted acepta que no har&#225; nada de los siguiente: (a) realizar reparaciones o modificaciones, o alterar de cualquier manera el Equipo; (b) Quitar o alterar cualquier marcador y certificados fijados al Equipo; (c) Compartir el Equipo con terceras personas, o permitir que terceros usen el Equipo, con la sola excepci&#243;n de un miembro familiar, amigo o acompa&#241;ante que lo est&#233; acompa&#241;ando en su viaje; (d) botar el equipo; (e) conceder alg&#250;n inter&#233;s en el Equipo a terceros; o (f) usar el equipo con prop&#243;sitos ilegales. </p>
<p>Todas las devoluciones deber&#225;n ser hechas no despu&#233;s de dos (2) d&#237;as finalizada la Fecha de T&#233;rmino de Arriendo. El Equipo deber&#225; ser entregado en buenas condiciones de estado y funcionamiento. Usted asume todos los riesgos de p&#233;rdidas y da&#241;os desde la devoluci&#243;n de todos los componentes del Equipo a nuestra direcci&#243;n de entrega. </p>
<p>Nosotros ponemos a disposici&#243;n un seguro, el cual puede ser comprado por un valor adicional y el cual cubrir&#225; cualquier riesgo a nuestro Equipo. Este seguro le permitir&#225; cubrir p&#233;rdidas y adem&#225;s de otros da&#241;os que afecten el buen funcionamiento del Equipo despu&#233;s de un deducible seg&#250;n sea el modelo del equipo tomado en arriendo.</p>
<p>Usted podr&#225; cancelar su reserva sin riesgo de multa cuatro (4) d&#237;as antes de la Fecha de Inicio del Arriendo. Si las reservas son canceladas a partir de tres (3) d&#237;as antes de la fecha de inicio de arriendo, o durante el Per&#237;odo de Arriendo, usted deber&#225; pagar una cuota de t&#233;rmino anticipado. En el evento en que la entrega del Equipo haya sido ya iniciada, el costo de env&#237;o no podr&#225; ser devuelto. Adem&#225;s, no podr&#225;n ser devueltos los d&#237;as en que usted se encuentre en posesi&#243;n del Equipo.</p>
<p>Al usar este servicio, usted acepta y reconoce que est&#225; arrendando un Equipo dise&#241;ado especialmente para viajes, y que usted no obtiene ning&#250;n tipo de derecho sobre el Equipo. Usted acepta que nosotros mantendremos toda la propiedad del Equipo, incluyendo pero no limitado a las gu&#237;as de usuario y accesorios.</p>
<p>Si usted est&#225; arrendando este Equipo a nombre de una entidad, entonces usted asegura y garantiza que se encuentra completamente autorizado a formar parte de este Acuerdo en nombre de dicha entidad, y para comprometer a dicha entidad a los t&#233;rminos y condiciones expuestos en este Contrato de Arriendo. Usted adem&#225;s representa y garantiza que no est&#225; cometiendo ning&#250;n tipo de fraude o falsa representaci&#243;n al entrar a este Contrato de Arriendo.</p>
<p> Orbyta Mobile garantiza que el Equipo ser&#225; entregado en buenas condiciones de funcionamiento y estado, y que continuar&#225; funcionando de manera correcta durante el t&#233;rmino del Per&#237;odo de Arriendo.</p>
<p>Orbyta Mobile tiene el derecho de facturar al Cliente, en diferido, en cualquier momento despu&#233;s que el Equipo haya sido devuelto por alguno o todos los cargos por los cuales el Cliente deber&#225; ser responsable, en virtud del Contrato, si Orbyta es o no consciente de tales cargos  al momento de la Devoluci&#243;n del Equipo. Todos los cargos y otras cantidades facturadas conforme al Acuerdo ser&#225;n pagadas por el Cliente al t&#233;rmino del per&#237;odo de Arriendo, si no calculadas al t&#233;rmino del Per&#237;odo de Arriendo, entonces al momento de un requerimiento dado por Orbyta al Cliente.</p>
<p>En el caso de no poder cumplir la Garant&#237;a de Orbyta Mobile expuesta anteriormente, nuestra &#250;nica obligaci&#243;n y soluci&#243;n ser&#225; la de reparar o reemplazar el Equipo a nuestra costa. Si nosotros reemplazamos el Equipo, usted recibir&#225; el mismo Equipo, o uno razonablemente similar para utilizarlo por el resto del Per&#237;odo de Arriendo. Es de su obligaci&#243;n notificarnos de manera inmediata en el caso que usted experimente cualquier problema con el Equipo.</p>
<p>A excepci&#243;n de la garant&#237;a entregada anteriorment, la empresa no se hace responsable ni garantiza, ni condiciona, ya sea de manera expl&#237;cita, impl&#237;cita, estatutaria, o de otra manera, oral o escrita, respecto al equipo o a este contrato de arriendo. Nosotros no podemos garantizar que nuestro equipo funcionar&#225; de manera ininterrumpida o sin errores, que trabajar&#225; de manera correcta con todas las conexiones inal&#225;mbricas, que cumpla todas sus necesidades, o que cualquier servicio adicional al que usted acceda a trav&#233;s de la gu&#237;a de usuario sea ininterrumpido, libre de errores, o que satisfaga sus necesidades. No nos podemos hacer responsables de la legalidad, adecuaci&#243;n, precisi&#243;n, calidad u funcionamiento de cualquier servicio entregado por terceros. La empresa rechaza expresamente todas las garant&#237;as entregadas por terceros respecto al quipo, nuestro servicio de arriendo y cualquier sea un servicio externo. Orbyta Mobile expresamente niega y rechaza todas las otras garant&#237;as respecto al equipo, nuestro servicio de arriendo, y cualquier otro servicio accedido a trav&#233;s de nuestra gu&#237;a de usuario, ya sea de manera expresa o impl&#237;cita, incluido pero no limitado a las garant&#237;as impl&#237;citas de comercializaci&#243;n, apto para un prop&#243;sito espec&#237;fico, t&#237;tulo y no infracci&#243;n de derechos de terceros. Usted asume solo y exclusivamente responsabilidad por el uso del equipo y por su confianza en servicios de terceros.</p>
<p>En la medida y dentro de lo que est&#225; permitido por ley, ni la empresa ni sus ejecutivos, directores, empleados, contratistas, agentes y representantes ser&#225;n, en cualesquier sea el caso, responsables de los da&#241;os indirectos, morales, ejemplares, especiales, incidentales o indirectos de cualquier tipo, incluyendo y sin limitar la p&#233;rdida de datos o beneficios, p&#233;rdida de buena voluntad o reputaci&#243;n comercial, el costo de adquisici&#243;n o sustituci&#243;n de bienes y servicios  de cobertura o da&#241;os de confianza, o cualquier otra p&#233;rdida tangible derivados en relaci&#243;n con este contrato, ya sea que dicha responsabilidad sea derivada de cualquier reclamo por contrato, garant&#237;a, agravio (incluyendo negligencia), responsabilidad estricta, violaci&#243;n de la propiedad intelectual, o cualquier otra forma, o en el caso en que no se nos haya advertido de la posibilidad de dicha p&#233;rdida o da&#241;o. acordamos que estas limitaciones sobrevivir&#225;n y ser&#225;n aplicadas, incluso, si cualquier recurso limitado especificado en este contrato haya fallado en su prop&#243;sito esencial. toda nuestra responsabilidad para cualesquiera sean las causas de acci&#243;n y bajo cualquier teor&#237;a de responsabilidad ser&#225; limitada y no exceder&#225; a la cantidad total de todos los gastos pagados por usted bajo este Contrato de Arriendo.</p>
<b><a id="english-tc">TERMS AND CONDITIONS</a></b>
<p>It is your own responsibility to read and understand these terms and conditions. If you had any kind of concern, please do not hesitate to contact Orbyta mobile on telephone support or email, indicated on the Orbyta website. 
Before you click on the &quot;accept&quot; button, please carefully read the terms and conditions set forth hereunder. By clicking on the &quot;accept&quot; button, you are bound by and have become a party to this agreement. We reserve the right to amend this rental agreement at any time. Any such changes will apply to future rentals after the date on which such amendment goes into effect.</p>
<p>Orbyta mobile llc (&#8220;Orbyta mobile&#8221;), and yourself (the &#8220;customer&#8221;) agree to the following terms and conditions: </p>
<p>Orbyta mobile will provide a wireless modem rental service (the &#8220;pocket wifi&#8221;), along with user guides and accessories (collectively the &#8220;equipment&#8221;) to travelers who plan to visit the United States of America.</p>
<p>While our equipment may be used by travelers of any age, we will only rent to adults who are at least 18 years of age and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in this rental agreement, and to abide by and comply with the terms and conditions set forth in this document.</p>
<p>You agree to exercise reasonable care in the use of all equipment, and to handle all equipment in accordance with the user guide. You further agree that you will not do any of the following: (a) make repairs or modifications, or alter in any way the equipment; (b) remove or alter any certification markers affixed to the equipment; (c) share the equipment with any third party, or allow any such third party to use the equipment with the sole exception of a family member, companion or friend accompanying you on your trip; (d) dispose of the equipment; (e) grant any interest in the equipment to any third party; or (f) use the equipment for any illegal purpose.</p>
<p>All returns must be delivered before two (2) days finished the end rental date. The equipment must be delivered in good shape and working conditions. You will assume all risks of loss and damage from the return of all equipment components to our shipping address.</p>
<p>We provide insurance, which may be purchased for an additional charge and will cover any risk of damage to our equipment. This insurance will provide coverage for damages and losses, plus other damages that might affect the good functioning of the equipment after a deductible, depending on the modem leased.</p>
<p>You may cancel your reservation without penalty risk four (4) days prior the rental start date. If reservations are cancelled within three (3) days before the rental start date or during the rental period, you will be charged an early termination fee. In the event that the equipment delivery has been initiated, the delivery cost cannot be refunded. In addition, no days can be refunded wherein you were in possession of the equipment.</p>
<p>When using this service, you agree and acknowledge that you are renting an equipment specially designed for travelling purposes only, and that you will acquire no rights in the equipment, including but not limited to user guides and accessories.</p>
<p>If you are renting this equipment on behalf of an entity rather than your own personal use, then you represent and will warrant that you are fully authorized to enter into this agreement on behalf of such entity, and to bind such entity to the terms and conditions set forth in this rental agreement. You further represent and warrant that you are not committing any fraud or misrepresentation in entering this rental agreement.</p>
<p>Orbyta mobile warrantees that the delivered equipment is in good shape and functioning conditions, and that will continue to operate properly during the term of the rental period.</p>
<p>Orbyta Mobile has the right to charge the Customer, delayed, at any time after the Equipment has been returned by any or all of the charges for which the Customer shall be responsible, under the Contract, whether or not Orbyta aware such charges at the time of Return of Equipment. All fees and other amounts billed under the Agreement shall be paid by the customer at the end of the period of Rent, if calculated at the end of the Lease Period, then the time of a given requirement Customer Orbyta</p>
<p>In the event of any failure to meet the company warranty set forth above, our sole liability and your sole and exclusive remedy will be to repair or replace the equipment at our expense. If we replace the equipment, you will receive the same or reasonably the same equipment to use for the remainder of the rental period. It is your obligation to notify the company immediately in the event that you experience any problems with the equipment.</p>
<p>Except for the warranty set forth, company makes no representations, warranties, conditions, or guaranties, whether express, implied, statutory, or otherwise, oral or written, regarding the equipment or this rental agreement. We make no endorsements regarding any third party listed in our user guide, and cannot warrant or make any representation about the quality of their services. We cannot warrant our equipment will operate uninterrupted or error-free, that it will operate properly on all wireless networks, that it will meet all of your needs, or that any third party services that you access through the user guide will be uninterrupted, error-free, or meet your needs. We cannot be responsible for the legality, adequacy, accuracy, quality, or operation of any third party services. Company expressly disclaims all other warranties with respect to the equipment, our rental services, and any third party services accessed through our user guide, whether express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement of third party rights. You assume sole and exclusive responsibility for the use of the equipment and for any reliance on any third party services.</p>
<p>To the extent and within what is permitted by law, neither the company nor its officers, directors, employees, contractors, agents and representatives shall, in any event, responsible for any consequential damages, moral, exemplary, special, incidental or indirect damages of any kind including, without limitation, loss of data or profit, loss of goodwill or business reputation, cost of purchase or replacement of goods and services from trusted coverage damage, or any other tangible loss incurred in relation with this agreement, whether such liability is derived from any claim in contract, warranty, tort (including negligence), strict liability, violation of intellectual property, or any other form, or in the event that we have not been warned of the possibility of such loss or damage. We agree that these limitations will survive and will be applied even if any limited remedy specified in this agreement have failed of its essential purpose.  All our responsibility for whatever the cause of action under any theory of liability will be limited and will not exceed the total amount of all expenses paid by you under this rental agreement.</p>